CREATE DATABASE Gerir
Use Gerir

CREATE TABLE Usuários(
 Id UNIQUEIDENTIFIER PRIMARY KEY,
 Nome VARCHAR(150) NOT NULL,
 Email VARCHAR(150) NOT NULL,
 Senha VARCHAR(150) NOT NULL,
 Tipo VARCHAR(100) NOT NULL,
) 

CREATE TABLE Tarefas( 
 Id UNIQUEIDENTIFIER PRIMARY KEY,
 Título VARCHAR(150) NOT NULL,
 Descrição TEXT NOT NULL,
 Categoria VARCHAR(150) NOT NULL,
 DataEntrega DATETIME NOT NULL,
 Status BIT NOT NULL,
 Usuario_Id UNIQUEIDENTIFIER
 FOREIGN KEY (Usuario_Id) REFERENCES Usuários(Id) ON DELETE CASCADE 
 )